apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-scheduler-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-scheduler-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-scheduler-rb
subjects:
- kind: ServiceAccount
  name: cronjob-scheduler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cronjob-scheduler-role
  apiGroup: rbac.authorization.k8s.io
